version: '3'

services:
  nginx:
      image: nginx:1.13
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
      depends_on:
        - python

  python:
      build: ./python
      volumes:
        - ./python:/usr/src/app
      ports:
        - "8000:8000"